[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C",
    "link-arg=-s",
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C",
    "link-arg=-s",
]

[target.armv7-unknown-linux-gnueabihf]
rustflags = [
    "-C",
    "link-arg=-s",
]

[build]
target-dir = "native/target"