[package]
name = "python"
version = "0.1.0"
authors = ["Lennart Voorgang <lennart@voorgang.eu>"]
edition = "2018"

[lib]
name = "dlog_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.13.2", features = ["extension-module"] }

native = { path = "../native"}